# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

#Note by Kenny:
#All environment databases point to the same test db on heroku (Gold)
#When deployed on heroku, we should be using the 'white' db
development:
  adapter: postgresql
  encoding: unicode
  host: ec2-54-235-174-213.compute-1.amazonaws.com
  database: dfbhkfeekdmih6
  user: ggprtclzftkrxr
  pool: 5
  port: 5432
  password: Y7hJ9w0ARZppxmLVu9CbxuDfSk

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
#This should point to the JADE database in heroku, or a local database
#This should NOT point to the prod database (WHITE on heroku) for reason stated above
test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: test
  username: postgres
  #password: H5Mckg14Hwn7xTDcMPnVrZYO1E
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  host: ec2-54-235-174-213.compute-1.amazonaws.com
  database: dfbhkfeekdmih6
  user: ggprtclzftkrxr
  pool: 5
  port: 5432
  password: Y7hJ9w0ARZppxmLVu9CbxuDfSk
